### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
#Normal list with loops
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2 = [2, 5, 9, 10, 12, 18, 0]
lista1 = []
lista2 = []
lista3 = []
for item in list:
    if item % 2 == 0:
        lista1.append(item)
print(lista1)

for item in list:
    if item in list2 and item % 2 != 0:
        lista2.append(item)
print(lista2)
for item in list2:
    if item not in list and item < 15:
        lista3.append(item)
print(lista3)

#List comprehension
list_cmp1 = [item for item in list if item % 2 == 0]
print(list_cmp1)
list_cmp2 = [item for item in list if item in list2 and item % 2 != 0]
print(list_cmp2)
list_cmp3 = [item for item in list2 if item not in list and item < 15]
print(list_cmp3)

[2, 4, 6, 8, 10]
[5, 9]
[12, 0]
[2, 4, 6, 8, 10]
[5, 9]
[12, 0]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [15]:
import numpy as np
my_array = np.array([2, 3, 5, 7])
print(len(my_array))
print(my_array.size)
my_array.dtype

4
4


dtype('int64')

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [ ]:
import random
a = np.arange(1, 11, 2)
b = a[2:]
c = a[-1::-1]
print(b)
print(a)
print(c)
print(a / c)

al = [1, 3, 5, 7, 9]
bl = al[2:]
cl = al[-1::-1]
print("\n")
print(al)
print(bl)
print(cl)
print([i / j for i, j in zip(al,cl)])



[5 7 9]
[1 3 5 7 9]
[9 7 5 3 1]
[0.11111111 0.42857143 1.         2.33333333 9.        ]


[1, 3, 5, 7, 9]
[5, 7, 9]
[9, 7, 5, 3, 1]
[0.1111111111111111, 0.42857142857142855, 1.0, 2.3333333333333335, 9.0]
